### ISSUE TITLE
ProductSearch Extensibility

### ISSUE THREAD

**Issue by ramniva** [OpenDirect/Spec-Review#10]
Possible to give the ProductSearch feature some extensibility? For example the NIVA ads requires filtering by: 
AvailDuration - min and max
Brand Categories - list of brand categories
Locale - list of locales

**Comment by ramniva** [comment]
I believe this search feature needs to be extensible for users to specify the various dimensions of search applicable to their inventory. Here are some search dimensions that pertain to TV shows and music videos.  

Content Owner
TV Show or Artist Name
Episode or Song Name
Avail Type - Product, Signage or Video
Avail Duration - min and max
Brand Category/Sub category
Locale/Sub-locale

**Comment by MelissaIAB** [comment]
This will be part of the larger channel support vote that's put up to the Task Force.  Putting this on hold until decide the group decides the next channel to provide additional support to.
