### ISSUE TITLE
Account associates with multiple Organization

### ISSUE THREAD

**Issue by pgdchayong** [OpenDirect/Spec-Review#12]
In Resource Model diagram (page 98), Brand B account associates with two Organizations, Coho Winery and Contoso, Ltd.
How would it be possible in the current Account / Organization model?
Organizations do not have account info. Accounts only allow one advertiser id and one buyer id.

**Comment by jpych** [comment]
Sorry for the delay @pgdchayong - here's the diagram.  The key thing is the `Account` is the connector between the buyer `Organization` (e.g. an agency) and the advertiser `Organization`.  This model allows a buyer to work with many advertisers and an advertiser to work with many buyers.  If the advertiser does their own buying, they'd be both the advertiser and the buyer.

Anyway, here's the ER diagram:

![untitled_clipping_010915_050950_pm](https://cloud.githubusercontent.com/assets/5912127/5688270/381029ba-9823-11e4-8672-d6f06499cc00.jpg)

Technically, `Organization` is the entity, but I split into buyer and advertiser above to hopefully add some clarity.

**Comment by pgdchayong** [comment]
Thanks for the clarification.
