### ISSUE TITLE
Video Support in Creative and Product

### ISSUE THREAD

**Issue by dnegstad** [OpenDirect/Spec-Review#18]
While the spec has token support for video creatives in the AdFormatType field, there are a number of fields that would be very handy for video units that aren't in the current spec version. I'd love to see a Duration(s) (in seconds) field added to the Creative object for video units, as well as more granular format types, such as VAST, VPAID, and VAST Tag (for wrapped units). Duration would likely need to allow for multiple values for Video units containing multiple optional assets.

For the Product object, I'd like to be able to expose information about Video products as to whether they're pre-roll, post-roll, or interstitial placements. I'd also like to be able to expose information about the maximum creative duration allowed for a particular product (15 second limit, 30 second limit, etc.)

**Comment by MelissaIAB** [comment]
Reviewing with the Video IAB lead here and getting her recommendation on this one.

**Comment by MelissaIAB** [comment]
I'm going to move this to HOLD.  We're going to wait for the Ads Formats Creative Guidelines to come out and then can address.
