### ISSUE TITLE
JSON Schema Definitions

### ISSUE THREAD

**Issue by dnegstad** [OpenDirect/Spec-Review#22]
I've been finding [JSON Schema](http://json-schema.org/) validations incredibly useful in setting up input sanitization for our ad server's API. I'd love to see schema definitions for the spec added to the repo. If there's any interest, I'd be more than happy to have my team help out in creating/maintaining them.

It'd make testing and validating data for companies implementing the API a lot easier.

**Comment by MelissaIAB** [comment]
I'm going to assign this to AdsNative
