### ISSUE TITLE
Workflow for Advertisers AND Publishers

### ISSUE THREAD

**Issue by regnyc** [OpenDirect/Spec-Review#30]
We need a workflow diagram that describes the publisher process, too.

**Comment by lucas084** [comment]
If we agree let's add to agenda for the next working session block

**Comment by MelissaIAB** [comment]
I'll add it as a roadmap item to be discussed and also a working session topic.  I agree this is needed.

**Comment by MelissaIAB** [comment]
GoogleDoc for Review.  Once Process is agreed up, the IAB will build the Workflow Diagram for review. 

https://docs.google.com/document/d/1DpX_pgIJd876FPQzUJLJqKG9yJ0THq-WXx2KK4gVtaE/edit?usp=sharing

**Comment by MelissaIAB** [comment]
marking this a reviewed in GitHub as group is currently working on reviewing.
