### ISSUE TITLE
Can we integrate Deal IDs in the spec?

### ISSUE THREAD

**Issue by regnyc** [OpenDirect/Spec-Review#32]
How come we didn't include Deal IDs in the spec?

**Comment by MelissaIAB** [comment]
Build out spec to include flag for order  A. PMP  B. Direct deal - then build out on how they are to be executed. 
*working session*

**Comment by MelissaIAB** [comment]
For reference, OpenRTB 2.2 provides support for DealID - http://www.iab.net/media/file/OpenRTBAPISpecificationVersion2_2.pdf]

This should be reviewed before the Working Session.

**Comment by MelissaIAB** [comment]
This is a nice to have item.  Going to put on hold after recommendation from DAATF
