### ISSUE TITLE
Expand Capabilities for Native Advertising

### ISSUE THREAD

**Issue by regnyc** [OpenDirect/Spec-Review#33]
InVideo, Audio, etc.

**Comment by ramniva** [comment]
It would be useful to add inputs related Native Advertising, including Mirriad's Native in-Video Advertising.

**Comment by MelissaIAB** [comment]
Will review the Native Ads Extension before pushing forward with roadmap item.

**Comment by MelissaIAB** [comment]
Here is the OpenRTB Native Ads Extension - http://www.iab.net/media/file/OpenRTB-Native-Ads-Specification-1_0-Final.pdf

Need to review to see if this provide enough support for native.

**Comment by ramniva** [comment]
Product Placement is a form of native that is in-video. Do not see that in this Native spec document. Will discuss in depth.
