### ISSUE TITLE
AdFormatTypes property should be added to Line and ProductAvailsSearch

### ISSUE THREAD

**Issue by harshal10** [OpenDirect/Spec-Review#35]
As a product can have multiple AdFormatTypes, line objects needs to have AdFomatTypes. Also, avails/pricing may vary as per AdFormatTypes so, ProductAvailsSearch should also specify AdFormatTypes.

**Comment by lucas084** [comment]
Is it enough to dictate Expandable vs NonExpandable?

**Comment by lucas084** [comment]
Art Size should always be required in an avails call

**Comment by MelissaIAB** [comment]
geometries associated with the product, are required. if system doesn't support, only upload products that have single geometry and avails associated.
