### ISSUE TITLE
Product and creative level reporting

### ISSUE THREAD

**Issue by SangeethAloysius** [OpenDirect/Spec-Review#37]
Currently reporting is limited to aggregated stats at both line and order level. This is not adequate and needs to have product and creative level reporting as well.

**Comment by MelissaIAB** [comment]
Need to explore.  Ramona will follow-up,

**Comment by jpych** [comment]
Reporting on creative is really important. Use cases to consider:
1) seller rotates the creative and has the numbers
2) buyer rotates the creative - seller does not have numbers because they are just using 1 tag

**Comment by MelissaIAB** [comment]
re-opening this for discussion.

**Comment by MelissaIAB** [comment]
1. If use case number 2, the spec already handles
2. With use case 1, if the buyer is taking that approach, reporting probably doesn’t matter.  

Group decision, the spec will not support at this time.
