### ISSUE TITLE
Negotiation (buy and sell side)

### ISSUE THREAD

**Issue by Showtunes** [OpenDirect/Spec-Review#38]
Recognizing that the OpenDirect standard was written from a demand partner perspective I'm still finding it hard to recognize where the negotiation between advertiser and publisher happens. Once the advertiser has submitted what's basically an electronic insertion order into a sell side platform, where in the API specification does the negotiation on CPM, flight dates, impressions or targeting data occur? How is the electronic insertion order sent back to an advertiser for further consideration before the campaign is agreed upon?

**Comment by jpych** [comment]
At present, OpenDirect doesn't support negotiation.  Just ordering.  That's certainly something that has been considered all along.  Question is if and when this should be included in the spec.

**Comment by lucas084** [comment]
For not the expectation is that this negotiation happens offline and is then reflected by what the publisher uploads in the tool.

**Comment by lucas084** [comment]
Could this be handled via a standard method for messaging?

**Comment by MelissaIAB** [comment]
everybody agrees on call
