### ISSUE TITLE
Compliance with OpenDirect

### ISSUE THREAD

**Issue by MelissaIAB** [OpenDirect/Spec-Review#40]
The OpenDirect 1.0 spec doesn't include a section for compliance. For the next release, perhaps we can even do a smaller release to include this, there should be a section around what are the min requirements in order for platforms to be compliant with OpenDirect. Then we can add OpenDirect to our IAB compliance program.

**Comment by MelissaIAB** [comment]
putting this on hold as this is a larger IAB Tech Lab discussion

**Comment by jpych** [comment]
In a perfect world, the IAB would develop a test suite and a compliance service.  And a directory of certified OpenDirect implementations.

**Comment by MelissaIAB** [comment]
It's on the roadmap!  We are putting openDirect up on our website for self-attestation.  Beyond that, in order for us to develop a full complaince program, the group will need to decide what is needed (is simply just adhering to ALL required fields or is it more nuanced?) within the protocol to determine compliant.

**Comment by MelissaIAB** [comment]
https://github.com/OpenDirect/Spec-Review/issues/43

OpenDirect 1.5 should have a compliance section.
