### ISSUE TITLE
AdID Support

### ISSUE THREAD

**Issue by MelissaIAB** [OpenDirect/Spec-Review#41]
Suggestion was put forth to make it a requirement to have AdID (first 5 digits) be the name of the creative file name in order to find the unique identifier (ad id)

**Comment by lucas084** [comment]
Should we provide a real field for the ID?

**Comment by MelissaIAB** [comment]
Angelina to provide workflow to walk group through at working session.

**Comment by jpych** [comment]
Since Ad-ID already embeds in the creative assets, OpenDirect does not need additional fields. If you want the Ad-ID data, you can just inspect the creative file.

**Comment by MelissaIAB** [comment]
Discussed at working session.  Closing out.
