### ISSUE TITLE
Localization for product names etc?

### ISSUE THREAD

**Issue by toukovk** [OpenDirect/Spec-Review#42]
At the moment entities like product have single "Name" - do you have any plans for localization?

**Comment by MelissaIAB** [comment]
Discussion for IAB.

**Comment by jpych** [comment]
This is similar to the discussion we had around handling multi-currency. The decision was not to handle multi-currency in a single product.  Rather, for each currency a separate product through the API.  Keep in mind that the implementation may store multi-currency on a single product and burst it out as multiple products via OpenDirect.

Likewise, we can take the same strategy with spoken language.  Each OpenDirect `product` should indicate its language.
