### ISSUE TITLE
Are publisher-specific extra fields allowed in resources?

### ISSUE THREAD

**Issue by toukovk** [OpenDirect/Spec-Review#43]
With brief searching, I didn't find a mention whether extra publisher-specific fields are allowed or not in resources?

Response resources:
- Is it allowed for a publisher to include extra fields in responses?
  - (In addition to ProviderData currently included in some resources.)

How about in request resources?
- Requiring extra fields in requests would make implementation incompatible with the spec, I suppose.
- How about publisher-specific extra fields in requests that would be used by the publisher if available (but not required)?

EDIT: Updated the comment after @MelissaIAB 's comment (replaced "provider" with "publisher")

**Comment by MelissaIAB** [comment]
Is this specific to publisher or the consumer?

**Comment by toukovk** [comment]
Publisher. To make the issue more clear, I'll edit the title & issue (replace my usage of "provider" with "publisher")

**Comment by jpych** [comment]
Although maybe not spelled out in the spec, I know early discussions (before IAB took it over) allowed vendors could extend the spec.  The spec would act as a least common denominator.  At least, that's my recollection of discussions that took place quite a while ago.

**Comment by MelissaIAB** [comment]
I think this goes to a larger compliance discussion.  We probably need an explicit compliance section within the protocol which spells out what it means to be OpenDirect compliant.

**Comment by jpych** [comment]
Compliance would mean following the spec.  But thinking it would not be a problem to go beyond the spec with additional fields. That extension would come at the risk of limiting trading partners to only those that support the proprietary extensions.

**Comment by MelissaIAB** [comment]
Closing this and tagging it to the larger compliance discussion.
