### ISSUE TITLE
Product:productTags: Array of Strings or Single space-separated String?

### ISSUE THREAD

**Issue by toukovk** [OpenDirect/Spec-Review#44]
Product resource definition for the property productTags has
- type: String[]
- description: "List of tags used for searching the product catalog."

However, the examples have the property as a single string:

```
  "productTags":"Foo Bar Zoo",
```

I suppose this is a typo and productTags should be a JSON array like:

```
  "productTags": ["Foo", "Bar", "Zoo"],
```

What do you think?

**Comment by jpych** [comment]
I agree. That seems like a typo. The tags should come back in an array vs. one long string.

**Comment by MelissaIAB** [comment]
will put in the OpenDirect 1.5 roadmap.

**Comment by katiestroudpro** [comment]
Changed data type FROM string TO array 

(there are actually a few places where string is identified as the data type, but a list is specified.)
