### ISSUE TITLE
AdFormatType(s) plural vs singular ambiguity in specification vs JSON examples

### ISSUE THREAD

**Issue by tsillan** [OpenDirect/Spec-Review#45]
According to the tables in the specification, the Product and ProductSearch entities have an  "AdFormatTypes" property (plural). However, the example JSON responses for /products and /products/{id} have "adFormatType" (singular). Similarly, the example JSON request for /products/search has "adFormatType". Potential implementors cannot know which one is correct. With other properties, such as ProductTags, a plural form is used both in the specification (tables) and examples.

**Comment by MelissaIAB** [comment]
will need to dig into spec.  see what needs updated if anything.

**Comment by jpych** [comment]
agreed it should be consistent.

**Comment by MelissaIAB** [comment]
adding this to the 1.5 roadmap

**Comment by katiestroudpro** [comment]
The plural term is the correct term for the property under Product and ProductSearch because the content for the data type is a list. I also updated the data type FROM string TO array since the content here is a list. The JSON example code has been updated to the plural format.
