### ISSUE TITLE
Using GET vs POST for /products/search and /products/avails

### ISSUE THREAD

**Issue by tsillan** [OpenDirect/Spec-Review#46]
The JSON example on page 81 of the v1.0 Final specification uses the HTTP request method GET for /products/search while other places in the document indicate the POST method should be used. The same ambiguity is also present in the example for /products/avails. Which method is correct? Ambiguities should be corrected to avoid incompatible implementations.

The /products/search resource expects search criteria in the request body (in JSON format) and therefore using the GET method is not a good idea, e.g. because of potential caching issues and incompatibility with HTTP client libraries (for discussion of reasons see http://stackoverflow.com/questions/978061/http-get-with-request-body and for for discussion on using GET or POST for restful search see http://stackoverflow.com/questions/5020704/how-to-design-restful-search-filtering).

**Comment by jpych** [comment]
That's a good point. If the search criteria is simple, then it can be passed as params in the GET. But that breaks down when the criteria is complex.

**Comment by MelissaIAB** [comment]
adding this to the 1.5 roadmap to clean up any ambiguities between post/get

**Comment by katiestroudpro** [comment]
The inconsistencies I found use GET or POST in the table but use the opposite in the example. I don't know if I can just change these. I'll need someone to go through and clean these up. Do we need a table of the inconsistencies for the group to review and decide whether it should be GET or POST?
