### ISSUE TITLE
Definitions for different numeric types (long/short/byte/decimal)

### ISSUE THREAD

**Issue by toukovk** [OpenDirect/Spec-Review#47]
There are various numeric types used in the spec, with brief looking I found at least the following ones:  long, short, byte and decimal.

However, I couldn't found definition for the different types from the spec.

As there is no common unambiguous definition for different numeric types and JSON doesn't have one, it would probably be good to add definition of used numeric types to the spec?

**Comment by jpych** [comment]
I agree.

**Comment by MelissaIAB** [comment]
We will be creating an OpenDirect 1.5 version with an aim to be released early Fall.  OpenDirect 1.5 will contain fixes to bugs in the spec and an overall specification clean-up.

**Comment by MelissaIAB** [comment]
This will be added to OpenDirect 1.5.

**Comment by katiestroudpro** [comment]
I started a section near the end for definitions. Is that what we need? Or do we need something more specific like a table describing numeric types. (On a side note, I found a "size" type. What is that?)

**Comment by toukovk** [comment]
I would also consider how many different types are really needed? For example, is differentiation between long/byte/short sensible of could they be handled with one integer type and specify potential restrictions by field if there are some?
