### ISSUE TITLE
OAuth 2.0 Access Token Usage

### ISSUE THREAD

**Issue by treidco** [OpenDirect/Spec-Review#48]
Can you please clarify how the OAuth 2.0 access token should be included in a request. The Authentication section of the OpenDirect v1 spec indicates that the access token should be passed as a header named AccessToken. In the relevant section of the OAuth 2.0 Bearer Token Usage RFC (https://tools.ietf.org/html/rfc6750#section-2) it states the access token should be included in the Authorization HTTP header.

**Comment by MelissaIAB** [comment]
AOL to follow-up
