### ISSUE TITLE
Creative Assignment

### ISSUE THREAD

**Issue by MelissaIAB** [OpenDirect/Spec-Review#50]
Request to update from AdSlot:

Currently the spec requires the assigning of a creative prior to order finalized.  This should be changed.

**Comment by MelissaIAB** [comment]
When I look at the the Resource Model Diagram, it seems to imply the creative is assigned to the account, not the creative, so this may not be an issue but would love group feedback.

**Comment by MelissaIAB** [comment]
Perhaps support publisher based setting. IAB to come up with proposal. On a product by product basis.

**Comment by katiestroudpro** [comment]
I added the value "AllowNoCreative" to the Product resource. This property is a Boolean value that indicates whether a line assigned to the product may be booked when no creative are assigned. Default is false and prevents booking when no creative is assigned. Does that work? Is something else needed?
