### ISSUE TITLE
Creative Approval Updates

### ISSUE THREAD

**Issue by MelissaIAB** [OpenDirect/Spec-Review#51]
Request from AdSlot:

There's no way for the spec to support approval changes, approved, rejected

**Comment by MelissaIAB** [comment]
The IAB also suggested a change in this area for the Creative Resource"

• AdQualityRejection
o   Update FROM “read only” TO an empty field for advertisers
o   Update FROM “read only” TO “optional” for publishers
 Should also provide table of common reasons for ad rejection
o   Remove “Quality” and update to “AdRejection”
 Would enable support of rejections such as wrong ad size
• AdQualityStatus
o   Update FROM “read only” TO an empty field for advertisers
o   Update FROM “read only” TO “optional” for publishers
o   Remove “Quality” and update to “AdStatus”

**Comment by MelissaIAB** [comment]
Update to:
*Status
*RejectionReason

**Comment by katiestroudpro** [comment]
Sections 1.3.3 and 1.3.4 updated. If we're going to provide a list of rejection reasons, we need to come up with that list. Also, ADD STATE and UPDATE state are always read-only or optional. Was it these two properties that needed to change to "empty field for advertisers?" If so, has "optional" been used universally to be a placeholder for fields that advertisers can edit? If not, how do we denote those?
