### ISSUE TITLE
Spec Clarification:  Publisher Defined Values

### ISSUE THREAD

**Issue by MelissaIAB** [OpenDirect/Spec-Review#55]
The following came in from a user trying to implement the spec:

The standard Target types with publisher defined values, How does client know that we support, for example age ranges 18-25, 25-35, 35-45, 45-80 and not 18-45, 45-80?

Also, related to this Product entity shows IDs of supported target types:
"targetTypes":["2342","3355"],

However, how those IDs can be mapped to types (Age, Gender)? We didn’t find an API specification for that.

The IDs in example below are useless for client, those are just numeric IDs and there is no way to map them to target type (Age, Gender or whatever else). In other words, client can’t know what is behind those IDs.

@lucas084, @cstodgel, @sudhamahajan, @jpych, - Do you think we could provide more clarify in the examples to avoid this type of confusion?

**Comment by jpych** [comment]
Take a look at `TargetValue` on page 52 of the current spec.  The example above can be handled by the spec as follows:

| Id | Value | TargetId |
| --- | --- | --- |
| 100 | 18-25 | 555 |
| 101 | 25-35 | 555 |
| 102 | 35-45 | 555 |
| 103 | 45-80 | 555 |

The values in the `Id` column are generated by  the publisher. "555" is the TargetId for the Age `Target`.
