### ISSUE TITLE
Draft 1.5 - Questions

### ISSUE THREAD

**Issue by ghost** [OpenDirect/Spec-Review#61]
Hello,

Reading the v1.5 draft internally, we had some questions, if somebody can jump-in and clarify, it would be very helpful !
- **Are discounts handled in the specs, and if yes, how would it work ?**
  - p23 on organization status : “This state may affect the products and pricing offered to the organization”
- **Are premium handled in the specs, and if yes, how would it work ?**
  - p24 “The product’s base retail price; this is not the rate card price. The actual price may be more if targeting is specified.”
- **Is it mandatory to use DigitalEnvoy ?**
  - p44, for TargetValue, DMA : "Source is DigitalEnvoy"
- **Versioning : does it refer to OpenDirect versions (1, 1.5, 2, etc) or the publisher API versions ?**
- **Can we specify publisher defined segments, and if yes, how (mentioned p44) ?**

Thanks !

**Comment by robynp** [comment]
**Discounts**
Discounts are not handled directly in v1.5. The usual current practise is to either use the “net” (or “net net”) price as the Buy price or use the “gross” as the Buy price and handle the discounts during invoicing. Maybe something to look at for v2.0

**Targeting Premium**
The actual price is returned in “ProductAvails” as a response to the “ProductAvailsSearch” which would specify any requested targeting

**DigitalEnvoy**
Any "reputable" geo service should be allowed. May be possible to extend the spec in v2 to show the data provider to targeting option

**Versioning**
This would need to be the Publisher's version number 

**Segments**
Define a Target eg "Model of Car", define the supported Target Values eg "Audi, Citroen, Ford, Toyota, VW". A Segment is then as a Target combined with one or more  Target Values eg "Model of Car = Audi, VW"
