### ISSUE TITLE
Timezone values standard

### ISSUE THREAD

**Issue by aroslov** [OpenDirect/Spec-Review#63]
Currently any value is allowed in timeZone field, we should have some standard. 

Based on experience, given all the day light saving time (DST) issues, TZ location names work very well, as they are specific, more granular and human readable 

See TZ in https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

**Comment by MelissaIAB** [comment]
If you look at date, there's a clear ISO standard which can be applied to time zone.  Essentially reference UTC.

**Comment by aroslov** [comment]
Sorry I wasn't very clear originally. I mean page 24 timezone field, and examples like on page 86:

 "timeZone":"Eastern Standard Time"

One more thing: UTC-5 for EST only works when there is FULL DATE AND TIME provided. Otherwise you can't establish the timezone meant int , as you don't know the day light saving. 

Normally in this cases, TZ locations are used in place of timezone.
