### ISSUE TITLE
Issue with the "sum of all weights is 100"

### ISSUE THREAD

**Issue by aroslov** [OpenDirect/Spec-Review#64]
Requirement  "the sum of all weights is 100” in section 2.2 is not very practical:

Consider use cases:
1) 2 creatives are already present with 40:60 split, and a new one with weight = 30 is added. Technically it may be impossible to ensure constant sum of 100, i.e. have this creation and update happen at the same time. 
2) 3 creatives are present, one of the creatives becomes inactive (e.g. declined) and the sum is no longer 100. An additional change (and business logic) is required to monitor this and update weights accordingly.

Proposal: drop “sum of 100” requirement. The publisher should serve the creative with frequency of Weight / Sum(all Weights).

**Comment by MelissaIAB** [comment]
Not all ad servers support this model.  We can revisit in Version 2.0
