### ISSUE TITLE
Clarification: AdPosition definition

### ISSUE THREAD

**Issue by aroslov** [OpenDirect/Spec-Review#65]
Please clarify the definition of “visible”.

Options:
- fully visible, i.e. 100% of pixels
- 50% of pixels (like in MRC/IAB viewability standard)
- something else? 

Seems like >=50% pixels on screen is preferable as compatible with viewability definition. 

Another option is to replace this field with historic viewability, like being discussed in OpenRTB, https://github.com/openrtb/OpenRTB/wiki/Proposal-for-Viewability-in-OpenRTB

**Comment by MelissaIAB** [comment]
will add to V2 roadmap.  publishers can define MRC attribute. 

Will clarify what visable means in regards to seeing the ad without scrolling.

**Comment by aroslov** [comment]
That is seeing 50% of pixels without scrolling? On which device?
