### ISSUE TITLE
Draft 1.5 - Clarification needed : who creates organizations ?

### ISSUE THREAD

**Issue by ghost** [OpenDirect/Spec-Review#67]
Who create organizations ? not clear : it seems that there are contradictions in the draft
- p10 : "Advertiser ID may be generated by the buyer (agency) or by the publisher if the advertiser is also the buyer"
- p92 (same as p10) : "Advertisers may sign up directly with the publisher" & "the agency may create organizations for their advertising clients"
- p80 (not saying the same), publisher always creating organizations “POST: (required) Adds an organization. Note that POST is not supported in the public API; it is included here for completeness. The process of adding advertiser and agency organizations and providing credentials is publisher defined.”
- p97 (here, publisher always create organizations) : “Have the publisher create an Organization for you and your advertising clients.”

We understood that p10 & p92 are correct e.g.
- if the organization is an agency, created by the publisher
- if the organization is an advertiser
  - if the buyer is the advertiser, organization created by the publisher
  - if the buyer is different : organization created by the buyer

Proposal : if this understanding is the right one, update the descriptions p80 & p97

**Comment by MelissaIAB** [comment]
Only publishers can create organization.  We will eliminate confusion around buyers creating organizations in the spec.

**Comment by ghost** [comment]
Is it be possible to let an agency create advertiser organizations when the agency is acting as the buyer ? It would be more efficient (no need for manual setup : asking the publisher to create an organization each time the agency is buying for a new advertiser)
Thanks

**Comment by robynp** [comment]
It was omitted because often Publishers wish to retain some control over who can advertise on their properties either for a certain period of time (eg. exclusivity for a vertical sold to a competitor) or completely (eg sumptuary laws). This becomes problematic if other parties can create Organisations without the necessary oversight.

**Comment by aroslov** [comment]
+1 to allow agencies create advertisers - this is a vital function and may cause unnecessary delays if workflow is not automated

@robynp section 2.6 for Organisations already describes the oversight method via the 'status' field, which allows Publishers accept / reject any new advertisers via OpenDirect and without any additional manual workflows.
