### ISSUE TITLE
Draft 1.5 - Clarification needed : can an advertiser have multiple organizations ?

### ISSUE THREAD

**Issue by ghost** [OpenDirect/Spec-Review#68]
There is a contradiction in the draft :
- p92 yes : “Once an organization has been added for the advertiser, the advertiser may create one or more organizations”
- p80 no : “The list will contain a single organization for advertisers”

We understood that an advertiser can indeed have multiple organizations
Proposal : if understanding correct, update p80

**Comment by MelissaIAB** [comment]
We will update page 80 to reflect what it says on 92.
