### ISSUE TITLE
Draft 1.5 - Clarification needed : permissions to search/reserve/book ?

### ISSUE THREAD

**Issue by ghost** [OpenDirect/Spec-Review#70]
In the specs, it's stated that the organization must have the status "Approved" or "Limited". If the advertiser and the buyer are different, do we have to check both organizations ?

Proposal : check both organizations as the advertiser & agency should both be "Approved" or "Limited"

**Comment by MelissaIAB** [comment]
Will make it clear in FAQ that both parties need to be in approved state.
