### ISSUE TITLE
Question: in AdFormatType whats the difference between HTML5 and Tag?

### ISSUE THREAD

**Issue by aroslov** [OpenDirect/Spec-Review#76]
Also how are these values represented in CreativeAsset? As a URL that points to HTML? As raw HTML?

**Comment by MelissaIAB** [comment]
A tag is a third party served ad.  This can contain an html5 or flash ad.  HTML5 would be the raw html5 served by the publisher. We will make this clear in the spec.

**Comment by aroslov** [comment]
Lets just drop "Tag' and introduce 'Flash'. Otherwise 'Tag' can be HTML5 and HTML5 is HTML5. Too confusing.
