### ISSUE TITLE
Extension fields

### ISSUE THREAD

**Issue by aroslov** [OpenDirect/Spec-Review#77]
Other IAB standards (OpenRTB, OpenRTB Native, VAST) allow protocol extensions via "ext" or "extensions" fields. 

In OpenDIrect there are ProviderData fields that are limited size CLOBs. Would be better to have unrestricted “extensions” fields at all levels, as it allows to pass custom structured data.

**Comment by MelissaIAB** [comment]
This applies to OpenRTB and wouldn't apply to OpenDirect.  Closing.

**Comment by aroslov** [comment]
The implementation doesn't need to be as in OpenRTB, but the feature is still required.

Otherwise how do propose parties extend the protocol beyond standard options?
