### ISSUE TITLE
Daily Budget and Quantity Caps

### ISSUE THREAD

**Issue by aroslov** [OpenDirect/Spec-Review#78]
Its common for advertisers to limit their daily spend.

Suggestion: add line.dailyQuantity and order.dailyBudget fields

**Comment by MelissaIAB** [comment]
This is only an issue for RTP. Not for direct buys.  Closing.

**Comment by aroslov** [comment]
What is RTP?

It is an issue in direct buys - almost every I/O we receive has such restrictions.
