### ISSUE TITLE
Brand Category

### ISSUE THREAD

**Issue by ramniva** [OpenDirect/Spec-Review#8]
The NIVA (Native In-Video Advertising) ad type has brand categories associated with it. Each NIVA avail has a one or more brand category associated with it. These are industry standard brand categories such as
Clothing & Accessories -->Clothes (Underwear & Sleepwear) -->Lingerie
Drink --> Hot Beverages --> Coffee Instant
Drink --> Beer, Lager & Cider

Request that this be added to search a product.

**Comment by MelissaIAB** [comment]
Is this a case unique to NIVA or could this be applied in other forms of advertising scenarios?

**Comment by ramniva** [comment]
Brand categories apply for any advertising campaign in general. However, my request here is to be able to specify a brand category for each NIVA avail within a video. I believe this feature applies in other forms of native ads too, since they are context dependent.

**Comment by MelissaIAB** [comment]
Right now it appears the specification references the former QAG categories (now the IAB Tech Lab Content Taxonomy).  Many of the IAB specs references this specific taxonomy.  This may be a request for the Taxonomy and Mapping Work Group versus the OpenDirect group which references an existing taxonomy.

**Comment by MelissaIAB** [comment]
Discussed with Group.  OpenDirect references the QAG categories (now the IAB Tech Lab Content Taxonomy). Updates to that taxonomy should go through the Taxonomy and Mapping Work Group.
