### ISSUE TITLE
Draft 1.5 - Clarification needed : who own accounts ?

### ISSUE THREAD

**Issue by ghost** [OpenDirect/Spec-Review#80]
Reading the specifications, it is not 100% clear if an advertiser own an account where the buyer is a different organization (agency). Does the advertiser own the account and so, is he allowed to perform actions on it ?

Hypothesis : yes
Proposition : clarify that both advertiser and buyer (if different) own an account

**Comment by lucas084** [comment]
The model is 1) an agency (the buying platform's customer) working to create campaigns for one or more advertisers. In this model, only the agency's users have access to campaign mgmt in the buying platform.  The advertiser is likely to only receive reports.

It is possible for 2)  the advertiser to be the customer as well, and create campaigns for themselves as the advertiser.  In this case an agency is not involved at all.
