### ISSUE TITLE
Organizations that support OpenDirect

### ISSUE THREAD

**Issue by remeniuk** [OpenDirect/Spec-Review#82]
Please excuse me for misusing the issues @OpenDirect discussion for my question but I couldn't find a more relevant place to ask this. 

Is there any page maintained by IAB/community that holds the list of sellers and buyers that support OpenDirect? Hopefully with some kind of roadmap and plan (e.g. Company X plans to support OpenDirect in 2016H2). If no, can we start using wiki for that matter?

**Comment by MelissaIAB** [comment]
Hello. http://www.iab.com/guidelines/understanding-iab-compliance-programs/
You can self-attest there.  Right now I'm only aware of two companies in the marketplace - yahoo and c1x that have adopted Opendirect. If others have adopted, they have yet to inform the IAB and self-attest.
