### ISSUE TITLE
Clarify use of Short data type

### ISSUE THREAD

**Issue by aroslov** [OpenDirect/Spec-Review#83]
A few objects use 'Short' data type, which is not defined in the document.

Since objects are described in JSON, and its natural to use JSON Schemas to validate requests and responses, and JSON doesn't have any notion of 'Short', suggest to change 'Short' to 'Integer'. 

Where needed, minimum and maximum constraints can be added.

**Comment by aroslov** [comment]
Similarly, spec references 'Byte' and 'Long' types, which can all be replaced with Integer as per JSON schema standard.

**Comment by robynp** [comment]
Update all short/long instances to "Integer" in v1.5.1
