### ISSUE TITLE
OrderStatus misleading documentation

### ISSUE THREAD

**Issue by aroslov** [OpenDirect/Spec-Review#84]
Currently OrderStatus documentation says "Returns a summary of lines for this order and the booking status for each. Array must contain line values for LineId paired with BookingStatus values for each line in the order. Line booking status values are described in section 2.4.1."

But OrderStatus field is not an array, its described as string. 

This field is also not present in any of the examples.

**Comment by robynp** [comment]
OrderStatus should only return a single status for the entire Order, not each Line item status.

Update to documentation in v1.5.1 is required
