### ISSUE TITLE
Incorrect type of Targeting field

### ISSUE THREAD

**Issue by aroslov** [OpenDirect/Spec-Review#85]
Page 16 says "Object". Must be "Array".

Page 32 says "Segment". Must be "Array" (or "Array of Segment")

**Comment by aroslov** [comment]
Same issue is with TargetValues on page 34

**Comment by aroslov** [comment]
Same issue is with Geometry on page 23 and page 33

**Comment by aroslov** [comment]
Same issue with InventoryType on page on page 24

**Comment by robynp** [comment]
These were fixed in the released version 1.5
