### ISSUE TITLE
Contradicting description of Quantity

### ISSUE THREAD

**Issue by aroslov** [OpenDirect/Spec-Review#91]
The table on page 32 says "Quantity" is "Required", at the same time "Description" reads "Leave field blank to return a product list with maximum availability for products specified."

So omitting the field is not an option (its "Required"), does this mean that the agency can be passing "quantity: null"?

Probably we should make this field "Optional"

**Comment by robynp** [comment]
Documentation to be changed to make "Quantity" Optional in v1.5.1
