### ISSUE TITLE
v1.5 - remove spaces in some property names

### ISSUE THREAD

**Issue by ghost** [OpenDirect/Spec-Review#93]
Sometimes, there is a space in a property name -- for consistency, it shouldn't be the case. Here is what we noted (to be completed if there are any other cases) :
- p20 : Change Pending ==> ChangePending
- p27 : change pending ==> ChangePending
- p37 : HTML5 Expendable ==> HTML5Expandable

**Comment by robynp** [comment]
Spaces to be removed in documentation for v1.5.1
