### ISSUE TITLE
Error in OpenDirect Workflow : Assignment

### ISSUE THREAD

**Issue by ghost** [OpenDirect/Spec-Review#95]
If we look at the Product ressource, there is a field called AllowNoCreative, described p26 : 

> A Boolean value that indicates **whether line items assigned to this order may be booked before creative is assigned**. A value of TRUE allows lines to be booked without creative assigned. Default value is FALSE and prevents lines from being booked when no creative is assigned.

But then, in the OpenDirect Workflow, there is a confusion : as if this boolean value indicated if a creative could be assigned to a line item depending on the creative status (confusion between booking a line where by default a creative should be assigned, and assigning a creative to a line where the publisher doesn't need to validate the creative first).

The errors, p92 :

> **In most cases, the creative must pass editorial review before it may be assigned to a line. The requirement to add creative before assignment is specified for the product**.

and p94 :

> Check for creative approval using the AdStatus property for the creative **
> **One approved, use the Assignment resource to assign the creative to a line**

Proposition : correct the workflow section as the creative status has to be checked only for booking, not for creative assignment

**Comment by robynp** [comment]
Should be reworded/corrected in v1.5.1
