### ISSUE TITLE
Product.Currency is an object?

### ISSUE THREAD

**Issue by A-Shevchenko** [OpenDirect/Spec-Review#97]
In specification v1.5 it's written that Product.Currency is an object. What kind of object? In example it's a string. Also, if product supports multiple currencies (BTW, is it supported), which one should be returned?

**Comment by robynp** [comment]
Currency should be a "String" referencing ISO 4217 values, documentation to be updated in v1.5.1 to reflect this.

Products available in multiple currencies would need to be returned as multiple products as a product can only contain one currency
